pipeline{
    agent{
        node{
            label "agent-1"
        }
    }
    stages{
        stage("init"){
            steps{
            """
                cd 01-vpc
                terraform init -reconfigure
            """
            }
        }

        stage("plan"){
            steps{
            """
                cd 01-vpc
                terraform plan
            """
            }
        }

        stage("apply"){
            input{
                message "should we continue?"
                ok "yes"
            }
            steps{
                """
                    cd 01-vpc
                    terraform apply -auto-approve
                """

                }
        }
    }

    post { 
        always { 
            echo 'I will always say Hello again!'
        }
        failure { 
            echo 'this runs when pipeline is failed, used generally to send some alerts'
        }
        success{
            echo 'I will say Hello when pipeline is success'
        }
    }
}
